import Report from "../models/report.model.js";

const getReportReason = (reasons = []) => {
  if (reasons.includes("bad_words")) return "bad_words";
  if (reasons.includes("suspicious_links")) return "suspicious_links";
  if (reasons.includes("spam")) return "auto_spam";

  return "other";
};

export const createAutoReport = async ({
  reporter,
  reportedUser = null,
  post = null,
  reel = null,
  comment = null,
  type,
  moderationReasons = [],
  description = "",
}) => {
  await Report.create({
    reporter,
    reportedUser,
    post,
    reel,
    comment,
    type,
    reason: getReportReason(moderationReasons),
    description:
      description || `Auto flagged by moderation system: ${moderationReasons.join(", ")}`,
    isAutoGenerated: true,
  });
};
